
export type FieldType = 'text' | 'textarea' | 'number' | 'date' | 'select' | 'checkbox' | 'multiselect';

export interface FormField {
  id: string;
  label: string;
  type: FieldType;
  options?: string[]; // for select/multiselect
  required?: boolean;
  category: string;
  active: boolean; // Customization: active or inactive
  description?: string; // Reason for collecting this data
  dependsOn?: { fieldId: string; value: string | boolean }; // Conditional logic
}

export const defaultFormFields: FormField[] = [
  { id: 'research_id', label: '(B) Araştırma ID (Otomatik Üretilir: GST-XXX)', type: 'text', category: 'Genel Bilgiler', active: true },
  { id: 'patient_age', label: '(E) Yaş', type: 'number', category: 'Genel Bilgiler', active: true },
  { id: 'patient_gender', label: '(F) Cinsiyet. 1: Erkek; 2: Kadın', type: 'select', options: ['1 - Erkek', '2 - Kadın'], category: 'Genel Bilgiler', active: true },
  { id: 'blood_type', label: 'Kan Grubu', type: 'select', options: ['A', 'B', 'AB', '0'], category: 'Genel Bilgiler', active: true },
  { id: 'clinical_notes', label: 'Klinik Notlar (Serbest Metin)', type: 'textarea', category: 'Genel Bilgiler', active: true },
  { id: 'consanguinity', label: 'Ebeveynler Arası Akrabalık Durumu (Konsanguinite Skalası)', type: 'select', options: ['Çift Taraflı 1. Kuzen', '1. Kuzen (Amca/Dayı/Hala/Teyze Çocuğu)', '1.5 Kuzen (Kuzen Çocuğu)', '2. Kuzen (Kuzen Torunu)', 'Bilinmiyor', 'Akrabalık Yok'], category: 'Konsanguinite ve Aile Kökeni', active: true, description: 'Akraba evliliği; resesif geçişli herediter sendromlar (MAP, Werner, Fanconi, homozigot CDH1) ve founder mutasyonlar açısından kritik risk bilgisidir.' },
  { id: 'consanguinity_type', label: 'Akrabalık Türü (serbest metin, örn: 1. kuzen / 2. kuzen)', type: 'text', category: 'Konsanguinite ve Aile Kökeni', active: true },
  { id: 'same_village', label: 'Ebeveynler Aynı Köy/Bölgeden mi? (Founder Mutasyon Riski)', type: 'select', options: ['Evet', 'Hayır', 'Bilinmiyor'], category: 'Konsanguinite ve Aile Kökeni', active: true },
  { id: 'family_origin_region', label: 'Ailenin Coğrafi Kökeni (örn: Doğu Anadolu, Güneydoğu, Karadeniz)', type: 'text', category: 'Konsanguinite ve Aile Kökeni', active: true },
  { id: 'personal_lobular_breast_ca', label: 'Kendisinde Lobüler Meme Kanseri Öyküsü Var mı? (HDGC İçin En Güçlü İpucu)', type: 'select', options: ['Evet', 'Hayır', 'Bilinmiyor'], category: 'Kişisel Tıbbi Öykü', active: true },
  { id: 'previous_other_cancer', label: 'Daha Önce Başka Kanser Geçirdi mi?', type: 'select', options: ['Evet', 'Hayır', 'Bilinmiyor'], category: 'Kişisel Tıbbi Öykü', active: true },
  { id: 'previous_other_cancer_type', label: 'Geçirdiği Diğer Kanser(ler) ve Tanı Yaşı', type: 'text', category: 'Kişisel Tıbbi Öykü', active: true, dependsOn: { fieldId: 'previous_other_cancer', value: 'Evet' } },
  { id: 'autoimmune_gastritis', label: 'Otoimmün Gastrit / Pernisiyöz Anemi Tanısı Var mı?', type: 'select', options: ['Evet', 'Hayır', 'Bilinmiyor'], category: 'Kişisel Tıbbi Öykü', active: true, description: 'H. pylori bağımsız atrofi yolu. Anti-pariyetal hücre antikoru kaydedilmeli.' },
  { id: 'gi_polyposis_history_personal', label: 'Kendisinde Gastrointestinal Polipozis Öyküsü Var mı?', type: 'select', options: ['Evet', 'Hayır', 'Bilinmiyor'], category: 'Kişisel Tıbbi Öykü', active: true, description: 'FAP, GAPPS, Peutz-Jeghers, JPS şüphesi; polip histolojisi ve sayısı önemli.' },
  { id: 'congenital_anomalies', label: 'Konjenital Anomali Öyküsü Var mı?', type: 'select', options: ['Evet', 'Hayır', 'Bilinmiyor'], category: 'Kişisel Tıbbi Öykü', active: true, description: 'Sendromik zemin araştırılmalı.' },
  { id: 'family_history', label: 'Aile Öyküsü Genel Özet (Serbest Metin)', type: 'textarea', category: 'Aile Hikayesi (Kanser Türüne Göre)', active: true },
  { id: 'family_gc', label: 'Ailede Mide Kanseri (Özellikle Diffüz Tip)', type: 'select', options: ['Var', 'Yok', 'Bilgi Yok'], category: 'Aile Hikayesi (Kanser Türüne Göre)', active: true, description: 'CDH1, CTNNA1, TP53, MLH1, APC promotor 1B ile ilişkili; IGCLC 2023 kriterleri.' },
  { id: 'family_lobular_breast', label: 'Ailede Lobüler Meme Kanseri', type: 'select', options: ['Var', 'Yok', 'Bilgi Yok'], category: 'Aile Hikayesi (Kanser Türüne Göre)', active: true, description: 'HDGC\'nin ikinci ana bileşeni (CDH1).' },
  { id: 'family_any_breast', label: 'Ailede Herhangi Bir Meme Kanseri (Özellikle Erken Başlangıçlı)', type: 'select', options: ['Var', 'Yok', 'Bilgi Yok'], category: 'Aile Hikayesi (Kanser Türüne Göre)', active: true, description: 'CDH1, BRCA1, BRCA2, PALB2, TP53 ile ilişkili.' },
  { id: 'family_crc_polyposis', label: 'Ailede Kolorektal Kanser veya Polipozis', type: 'select', options: ['Var', 'Yok', 'Bilgi Yok'], category: 'Aile Hikayesi (Kanser Türüne Göre)', active: true, description: 'Lynch (MLH1/MSH2/MSH6/PMS2), FAP (APC), MAP (MUTYH).' },
  { id: 'family_endometrial', label: 'Ailede Endometriyal (Rahim) Kanseri', type: 'select', options: ['Var', 'Yok', 'Bilgi Yok'], category: 'Aile Hikayesi (Kanser Türüne Göre)', active: true, description: 'Lynch sendromunun en sık ikinci tümörü.' },
  { id: 'family_ovarian', label: 'Ailede Over Kanseri', type: 'select', options: ['Var', 'Yok', 'Bilgi Yok'], category: 'Aile Hikayesi (Kanser Türüne Göre)', active: true, description: 'BRCA1/2, MLH1, MSH2, RAD51C/D ile ilişkili.' },
  { id: 'family_pancreatic', label: 'Ailede Pankreas Kanseri', type: 'select', options: ['Var', 'Yok', 'Bilgi Yok'], category: 'Aile Hikayesi (Kanser Türüne Göre)', active: true, description: 'BRCA2, PALB2, ATM, STK11 (Peutz-Jeghers).' },
  { id: 'family_prostate', label: 'Ailede Prostat Kanseri (Özellikle Agresif, Erken)', type: 'select', options: ['Var', 'Yok', 'Bilgi Yok'], category: 'Aile Hikayesi (Kanser Türüne Göre)', active: true, description: 'BRCA2, BRCA1, ATM, CHEK2.' },
  { id: 'family_sarcoma_brain_adrenal', label: 'Ailede Sarkom, Beyin Tümörü veya Adrenokortikal Karsinom', type: 'select', options: ['Var', 'Yok', 'Bilgi Yok'], category: 'Aile Hikayesi (Kanser Türüne Göre)', active: true, description: 'TP53 (Li-Fraumeni) şüphesi.' },
  { id: 'family_paraganglioma', label: 'Ailede Paragangliom / Feokromositom', type: 'select', options: ['Var', 'Yok', 'Bilgi Yok'], category: 'Aile Hikayesi (Kanser Türüne Göre)', active: true, description: 'SDHB/C/D genleri (Carney-Stratakis).' },
  { id: 'family_skin_tumors', label: 'Ailede Cilt Tümörleri (Sebase Adenom, Keratoakantom)', type: 'select', options: ['Var', 'Yok', 'Bilgi Yok'], category: 'Aile Hikayesi (Kanser Türüne Göre)', active: true, description: 'Muir-Torre sendromu (Lynch varyantı).' },
  { id: 'family_early_onset', label: 'Ailede <50 Yaşında Kanser Tanısı', type: 'select', options: ['Var', 'Yok', 'Bilgi Yok'], category: 'Aile Hikayesi (Kanser Türüne Göre)', active: true, description: 'Güçlü genetik şüphe göstergesi.' },
  { id: 'family_multiple_cancers', label: 'Ailede Aynı Kişide Birden Fazla Farklı Tip Kanser', type: 'select', options: ['Var', 'Yok', 'Bilgi Yok'], category: 'Aile Hikayesi (Kanser Türüne Göre)', active: true, description: 'Herediter sendrom göstergesi.' },
  { id: 'dysmorphic_lip_pigmentation', label: 'Mukokütanöz Pigmentasyon (Dudak, Ağız İçi, Parmak Uçları)', type: 'select', options: ['Evet', 'Hayır', 'Bilinmiyor'], category: 'Dismorfik Muayene Bulguları', active: true, description: 'Peutz-Jeghers (STK11) için ayırt edici bulgu.' },
  { id: 'dysmorphic_palmoplantar_keratosis', label: 'Palmar/Plantar Keratozis', type: 'select', options: ['Evet', 'Hayır', 'Bilinmiyor'], category: 'Dismorfik Muayene Bulguları', active: true, description: 'Howel-Evans sendromu (Tylosis, RHBDF2); özofagus ve mide kanseri riski.' },
  { id: 'dysmorphic_sebaceous_tumors', label: 'Sebase Deri Tümörleri (Adenom/Karsinom, Keratoakantom)', type: 'select', options: ['Evet', 'Hayır', 'Bilinmiyor'], category: 'Dismorfik Muayene Bulguları', active: true, description: 'Muir-Torre sendromu (Lynch varyantı, MMR).' },
  { id: 'dysmorphic_trichilemmoma', label: 'Trikolemal Kistler / Fasiyal Papüller / Yüz Trichilemmomları', type: 'select', options: ['Evet', 'Hayır', 'Bilinmiyor'], category: 'Dismorfik Muayene Bulguları', active: true, description: 'Cowden sendromu (PTEN)\'in patognomonik bulgusu.' },
  { id: 'dysmorphic_cafe_au_lait', label: 'Café-au-lait Lekeleri (≥6 adet) / Aksiller Çillenme', type: 'select', options: ['Evet', 'Hayır', 'Bilinmiyor'], category: 'Dismorfik Muayene Bulguları', active: true, description: 'Nörofibromatoz Tip 1 (NF1); GIST riski.' },
  { id: 'dysmorphic_tooth_agenesis', label: 'Konjenital Diş Agenezisi (Lateral Keser / 2. Premolar)', type: 'select', options: ['Evet', 'Hayır', 'Bilinmiyor'], category: 'Dismorfik Muayene Bulguları', active: true, description: 'CDH1 germline (HDGC) taşıyıcılarında bildirilmiş (PubMed 2025).' },
  { id: 'dysmorphic_skin_aging', label: 'Deri Atrofisi / Sklerodermi + Erken Yaşlanma Bulguları', type: 'select', options: ['Evet', 'Hayır', 'Bilinmiyor'], category: 'Dismorfik Muayene Bulguları', active: true, description: 'Werner sendromu (WRN); konsanguinite ile birlikte homozigot risk artar.' },
  { id: 'dysmorphic_nail_leukoplakia', label: 'Anormal Tırnaklar + Ağız İçi Lökoplakileri + Ağ Cilt Pigmentasyonu', type: 'select', options: ['Evet', 'Hayır', 'Bilinmiyor'], category: 'Dismorfik Muayene Bulguları', active: true, description: 'Diskeratosis Konjenita (DKC1/TERT/TERC); telomeropati.' },
  { id: 'dysmorphic_osteoma', label: 'Osteomlar (Mandibula/Kafatası) veya Desmoid Tümör', type: 'select', options: ['Evet', 'Hayır', 'Bilinmiyor'], category: 'Dismorfik Muayene Bulguları', active: true, description: 'Gardner sendromu (APC varyantı).' },
  { id: 'dysmorphic_chrpe', label: 'CHRPE - Konjenital Hipertrofik Retinal Pigment Epiteli (Fundoskopi)', type: 'select', options: ['Evet', 'Hayır', 'Bilinmiyor'], category: 'Dismorfik Muayene Bulguları', active: true, description: 'FAP (APC) ipucu.' },
  { id: 'dysmorphic_macrocephaly_lipoma', label: 'Makrosefali / Çoklu Lipomlar', type: 'select', options: ['Evet', 'Hayır', 'Bilinmiyor'], category: 'Dismorfik Muayene Bulguları', active: true, description: 'Cowden / PTEN / Bannayan-Riley spektrumu.' },
  { id: 'dysmorphic_other_notes', label: 'Diğer Dismorfik Bulgular (Serbest Metin)', type: 'textarea', category: 'Dismorfik Muayene Bulguları', active: true },
  { id: 'suspected_syndrome', label: 'Şüphelenilen Herediter Sendrom', type: 'select', options: ['HDGC (CDH1/CTNNA1)', 'Lynch Sendromu (MMR)', 'FAP', 'GAPPS', 'Peutz-Jeghers (STK11)', 'Li-Fraumeni (TP53)', 'MAP (MUTYH)', 'BRCA1/BRCA2', 'Diskeratosis Konjenita', 'Werner Sendromu', 'Cowden (PTEN)', 'Diğer', 'Yok / Şüphe Yok'], category: 'Sendrom Şüphesi ve Germline Test', active: true },
  { id: 'cdh1_germline', label: 'CDH1 Germline Sonucu (HDGC)', type: 'select', options: ['Patojenik (Pozitif)', 'Negatif', 'VUS (Belirsiz Anlamlı Varyant)', 'Test Yapılmadı'], category: 'Sendrom Şüphesi ve Germline Test', active: true },
  { id: 'ctnna1_germline', label: 'CTNNA1 Germline Sonucu (CDH1 Negatifse)', type: 'select', options: ['Patojenik (Pozitif)', 'Negatif', 'VUS', 'Test Yapılmadı'], category: 'Sendrom Şüphesi ve Germline Test', active: true },
  { id: 'mmr_germline', label: 'MMR Germline Sonucu (MLH1/MSH2/MSH6/PMS2 - Lynch)', type: 'select', options: ['Patojenik (Pozitif)', 'Negatif', 'VUS', 'Test Yapılmadı'], category: 'Sendrom Şüphesi ve Germline Test', active: true },
  { id: 'apc_germline', label: 'APC Germline Sonucu (FAP/GAPPS)', type: 'select', options: ['Patojenik (Pozitif)', 'Negatif', 'VUS', 'Test Yapılmadı'], category: 'Sendrom Şüphesi ve Germline Test', active: true },
  { id: 'mutyh_germline', label: 'MUTYH Germline Sonucu (Biallelik - MAP)', type: 'select', options: ['Biallelik Pozitif', 'Monoallelik (Taşıyıcı)', 'Negatif', 'Test Yapılmadı'], category: 'Sendrom Şüphesi ve Germline Test', active: true },
  { id: 'stk11_germline', label: 'STK11 Germline Sonucu (Peutz-Jeghers)', type: 'select', options: ['Patojenik (Pozitif)', 'Negatif', 'VUS', 'Test Yapılmadı'], category: 'Sendrom Şüphesi ve Germline Test', active: true },
  { id: 'tp53_germline', label: 'TP53 Germline Sonucu (Li-Fraumeni)', type: 'select', options: ['Patojenik (Pozitif)', 'Negatif', 'VUS', 'Test Yapılmadı'], category: 'Sendrom Şüphesi ve Germline Test', active: true },
  { id: 'wrn_germline', label: 'WRN Germline Sonucu (Werner Sendromu)', type: 'select', options: ['Homozigot Pozitif', 'Heterozigot (Taşıyıcı)', 'Negatif', 'Test Yapılmadı'], category: 'Sendrom Şüphesi ve Germline Test', active: true },
  { id: 'brca_germline', label: 'BRCA1/BRCA2 Germline Sonucu', type: 'select', options: ['BRCA1 Pozitif', 'BRCA2 Pozitif', 'Negatif', 'VUS', 'Test Yapılmadı'], category: 'Sendrom Şüphesi ve Germline Test', active: true },
  { id: 'germline_test_notes', label: 'Germline Test Notları / Panel NGS Sonucu (Serbest Metin)', type: 'textarea', category: 'Sendrom Şüphesi ve Germline Test', active: true },
  { id: 'per_durum', label: '(G) Per.Durum. 0: PS0; 1: PS1; 2: PS2; 3: PS3; 4: PS4; 5: BİLGİ YOK', type: 'select', options: ['0 - PS0', '1 - PS1', '2 - PS2', '3 - PS3', '4 - PS4', '5 - BİLGİ YOK'], category: 'Demografik & Yaşam Tarzı', active: true },
  { id: 'aile_oykusu', label: '(H) Aile Öyküsü (Genel). 0: YOK; 1: VAR; 2: BİLGİ YOK', type: 'select', options: ['0 - YOK', '1 - VAR', '2 - BİLGİ YOK'], category: 'Demografik & Yaşam Tarzı', active: true },
  { id: 'kilo_kaybi', label: '(I) Kilo Kaybı (Son 6 Ayda). 1: YOK; 2: VAR; 3: BİLGİ YOK', type: 'select', options: ['1 - YOK', '2 - VAR', '3 - BİLGİ YOK'], category: 'Demografik & Yaşam Tarzı', active: true },
  { id: 'sigara', label: '(J) Sigara. 1: YOK; 2: VAR; 3: BİLGİ YOK', type: 'select', options: ['1 - YOK', '2 - VAR', '3 - BİLGİ YOK'], category: 'Demografik & Yaşam Tarzı', active: true },
  { id: 'lokaliza', label: '(K) Lokalizasyon. 1: Distal; 2: Proksimal', type: 'select', options: ['1 - Distal', '2 - Proksimal'], category: 'Tümör Patolojisi & Evreleme', active: true },
  { id: 'kanser_tipi', label: '(L) Kanser Tipi. 1: Adenokarsinom; 2: Skuamöz Hücreli Ca; 3: Nöroendokrin Karsinom; 4: Lenfoma; 5: GİST', type: 'select', options: ['1 - Adenokarsinom', '2 - Skuamöz Hücreli Ca', '3 - Nöroendokrin Karsinom', '4 - Lenfoma', '5 - GİST'], category: 'Tümör Patolojisi & Evreleme', active: true },
  { id: 'histoloji_bormann', label: '(M) Histoloji Bormann. 1: Polipoid; 2: Fungal; 3: Ülseröz; 4: Diffüz İnfiltran; 5: Vegetan; 6: Ülsero Vegetan', type: 'select', options: ['1 - Polipoid', '2 - Fungal', '3 - Ülseröz', '4 - Diffüz İnfiltran', '5 - Vegetan', '6 - Ülsero Vegetan'], category: 'Tümör Patolojisi & Evreleme', active: true },
  { id: 'histoloji_who', label: '(N) Histoloji WHO. 1: Papiller; 2: Tubuler; 3: Müsinöz; 4: Taşlı Yüzük; 6: Kribriform; 7: Miks Histoloji; 8: Solid Patern', type: 'select', options: ['1 - Papiller', '2 - Tubuler', '3 - Müsinöz', '4 - Taşlı Yüzük', '6 - Kribriform', '7 - Miks Histoloji', '8 - Solid Patern'], category: 'Tümör Patolojisi & Evreleme', active: true },
  { id: 'histoloji_ming', label: '(O) Histoloji Ming. 1: İnfiltratif; 2: Ekspansif; 3: Expansif İnfitratif', type: 'select', options: ['1 - İnfiltratif', '2 - Ekspansif', '3 - Expansif İnfitratif'], category: 'Tümör Patolojisi & Evreleme', active: true },
  { id: 'lauren_classification', label: '(P) Lauren Sınıflaması. 1: Diffüz; 2: İntestinal', type: 'select', options: ['1 - Diffüz', '2 - İntestinal'], category: 'Tümör Patolojisi & Evreleme', active: true, description: 'Diffüz tip: HDGC (CDH1, CTNNA1) şüphesi. İntestinal tip: Lynch, FAP.' },
  { id: 'tm_api_cm', label: '(Q) Tümör Çapı (cm)', type: 'text', category: 'Tümör Patolojisi & Evreleme', active: true },
  { id: 't_stage', label: '(R) T Evresi. 1: T1a; 2: T1b; 3: T2; 4: T3; 5: T4a; 6: T4b', type: 'select', options: ['1 - T1a', '2 - T1b', '3 - T2', '4 - T3', '5 - T4a', '6 - T4b'], category: 'Tümör Patolojisi & Evreleme', active: true },
  { id: 'n_stage', label: '(S) N Evresi. 0: N0; 1: N1; 2: N2; 3: N3a; 4: N3b', type: 'select', options: ['0 - N0', '1 - N1', '2 - N2', '3 - N3a', '4 - N3b'], category: 'Tümör Patolojisi & Evreleme', active: true },
  { id: 'm_stage', label: '(T) M Evresi. 0: M0; 1: M1', type: 'select', options: ['0 - M0', '1 - M1'], category: 'Tümör Patolojisi & Evreleme', active: true },
  { id: 'tnm_stage', label: '(U) TNM Evre (Genel)', type: 'text', category: 'Tümör Patolojisi & Evreleme', active: true },
  { id: 'toplam_ln_sayisi', label: '(V) Toplam Lenf Nodu Sayısı', type: 'number', category: 'Tümör Patolojisi & Evreleme', active: true },
  { id: 'malign_ln_sayisi', label: '(W) Malign Lenf Nodu Sayısı', type: 'number', category: 'Tümör Patolojisi & Evreleme', active: true },
  { id: 'lenf_invazyon', label: '(X) Lenf İnvazyonu. 0: YOK; 1: VAR; 2: BİLGİ YOK', type: 'select', options: ['0 - YOK', '1 - VAR', '2 - BİLGİ YOK'], category: 'Tümör Patolojisi & Evreleme', active: true },
  { id: 'vask_infazyon', label: '(Y) Vasküler İnvazyon. 0: YOK; 1: VAR', type: 'select', options: ['0 - YOK', '1 - VAR'], category: 'Tümör Patolojisi & Evreleme', active: true },
  { id: 'perino_invazyon', label: '(Z) Perinöral İnvazyon. 0: YOK; 1: VAR; 2: BİLGİ YOK', type: 'select', options: ['0 - YOK', '1 - VAR', '2 - BİLGİ YOK'], category: 'Tümör Patolojisi & Evreleme', active: true },
  { id: 'grade', label: '(AA) Grade. 1: Grade 1; 2: Grade 2; 3: Grade 3', type: 'select', options: ['1 - Grade 1', '2 - Grade 2', '3 - Grade 3'], category: 'Tümör Patolojisi & Evreleme', active: true },
  { id: 'tasli_yuzuk', label: '(AB) Taşlı Yüzük Hücresi. 0: YOK; 1: VAR', type: 'select', options: ['0 - YOK', '1 - VAR'], category: 'Tümör Patolojisi & Evreleme', active: true },
  { id: 'her2_status', label: '(AC) HER2 Durumu. 0: Negatif; 1: 1+; 2: 2+; 3: 3+', type: 'select', options: ['0 - Negatif', '1 - 1+', '2 - 2+', '3 - 3+'], category: 'Tümör Patolojisi & Evreleme', active: true },
  { id: 'her2fish', label: '(AD) HER2 FISH. 0: Negatif; 1: Pozitif; 2: Bilgi Yok', type: 'select', options: ['0 - Negatif', '1 - Pozitif', '2 - Bilgi Yok'], category: 'Tümör Patolojisi & Evreleme', active: true },
  { id: 'musin', label: '(AE) Müsin. 0: YOK; 1: VAR', type: 'select', options: ['0 - YOK', '1 - VAR'], category: 'Tümör Patolojisi & Evreleme', active: true },
  { id: 'msi_status', label: 'MSI Durumu (Mikrosatellit İnstabilitesi)', type: 'select', options: ['MSI-H', 'MSI-Low', 'MSS (Stabil)', 'Bilgi Yok'], category: 'Moleküler Belirteçler', active: true, description: 'MSI-H → Germline MMR testi zorunlu (Lynch şüphesi, NCCN 2026).' },
  { id: 'ebv_ish', label: 'EBV-ISH Durumu', type: 'select', options: ['Pozitif', 'Negatif', 'Bilgi Yok'], category: 'Moleküler Belirteçler', active: true },
  { id: 'pdl1_cps', label: 'PD-L1 CPS Skoru', type: 'text', category: 'Moleküler Belirteçler', active: true },
  { id: 'cldn182', label: 'Claudin 18.2 (CLDN18.2) Durumu', type: 'select', options: ['Pozitif', 'Negatif', 'Bilgi Yok'], category: 'Moleküler Belirteçler', active: true },
  { id: 'h_pylori', label: 'H. Pylori Durumu', type: 'select', options: ['Pozitif', 'Negatif', 'Bilgi Yok'], category: 'Moleküler Belirteçler', active: true },
  { id: 'peritoneal_cytology', label: 'Peritoneal Sitoloji', type: 'select', options: ['Pozitif', 'Negatif', 'Bakılmadı'], category: 'Moleküler Belirteçler', active: true },
  { id: 'cer_turu', label: '(AF) Cerrahi Türü. 1: Total Gastrektomi; 2: Subtotal Gastrektomi; 3: Palyatif Rezeksiyon', type: 'select', options: ['1 - Total Gastrektomi', '2 - Subtotal Gastrektomi', '3 - Palyatif Rezeksiyon'], category: 'Cerrahi & Tedavi', active: true },
  { id: 'total_subtotal', label: '(AG) Total/Subtotal', type: 'text', category: 'Cerrahi & Tedavi', active: true },
  { id: 'rezeksiyon_tipi', label: '(AH) Rezeksiyon Tipi. 0: R0; 1: R1; 2: R2', type: 'select', options: ['0 - R0', '1 - R1', '2 - R2'], category: 'Cerrahi & Tedavi', active: true },
  { id: 'relaps', label: '(AI) Relaps. 0: YOK; 1: VAR; 2: BİLGİ YOK', type: 'select', options: ['0 - YOK', '1 - VAR', '2 - BİLGİ YOK'], category: 'Cerrahi & Tedavi', active: true },
  { id: 'lokal_nuks', label: '(AJ) Lokal Nüks. 0: YOK; 1: VAR; 2: BİLGİ YOK', type: 'select', options: ['0 - YOK', '1 - VAR', '2 - BİLGİ YOK'], category: 'Cerrahi & Tedavi', active: true },
  { id: 'lokal_nuks_tarihi', label: '(AK) Lokal Nüks Tarihi', type: 'text', category: 'Cerrahi & Tedavi', active: true },
  { id: 'metastaz_var_mi', label: '(AL) Metastaz Var Mı. 0: YOK; 1: VAR', type: 'select', options: ['0 - YOK', '1 - VAR'], category: 'Cerrahi & Tedavi', active: true },
  { id: 'metastaz_yeri', label: '(AM) Metastaz Yeri', type: 'text', category: 'Cerrahi & Tedavi', active: true },
  { id: 'metastaz_tarihi', label: '(AN) Metastaz Tarihi', type: 'text', category: 'Cerrahi & Tedavi', active: true },
  { id: 'neoadjuvan_tedavi', label: '(AO) Neoadjuvan Tedavi. 0: YOK; 1: VAR; 2: BİLGİ YOK', type: 'select', options: ['0 - YOK', '1 - VAR', '2 - BİLGİ YOK'], category: 'Cerrahi & Tedavi', active: true },
  { id: 'adjuvan_tedavi', label: '(AP) Adjuvan Tedavi. 0: YOK; 1: VAR; 2: BİLGİ YOK', type: 'select', options: ['0 - YOK', '1 - VAR', '2 - BİLGİ YOK'], category: 'Cerrahi & Tedavi', active: true },
  { id: 'adjuvan_tedavi_turu', label: '(AQ) Adjuvan Tedavi Türü. 1: KTRT; 2: Sadece KT', type: 'select', options: ['1 - KTRT', '2 - Sadece KT'], category: 'Cerrahi & Tedavi', active: true },
  { id: 'adjuvan_kt', label: '(AR) Adjuvan KT. 1: FUFA-RT; 2: FOLFOX RT; 3: XELOX RT; 4: Sadece KT; 5: Bilgi Yok', type: 'select', options: ['1 - FUFA-RT', '2 - FOLFOX RT', '3 - XELOX RT', '4 - Sadece KT', '5 - Bilgi Yok'], category: 'Cerrahi & Tedavi', active: true },
  { id: 'adjuvan_tedavi_kur_sayisi', label: '(AS) Adjuvan Tedavi Kür Sayısı', type: 'number', category: 'Cerrahi & Tedavi', active: true },
  { id: 'adjuvan_tedavi_tarihi', label: '(AT) Adjuvan Tedavi Tarihi', type: 'text', category: 'Cerrahi & Tedavi', active: true },
  { id: 'metastatik_durum', label: '(AU) Metastatik Durum. 0: Progresyon Sonrası; 1: Başlangıçta Metastatik', type: 'select', options: ['0 - Progresyon Sonrası', '1 - Başlangıçta Metastatik'], category: 'Metastatik Tedavi', active: true },
  { id: 'metastaz_tarihi_2', label: '(AV) Metastaz Tarihi (2)', type: 'text', category: 'Metastatik Tedavi', active: true },
  { id: 'metastaz_ilk_seri_kt_rejimi', label: '(AW) Metastatik İlk Seri KT Rejimi. 1: FUFA-XELODA; 2: FOLFOX/XELOX; 3: FOLFIRI/XELİRİ; 4: CF/CX; 5: DCF/DCX; 6: ECF/EOF/EOX/ECX; 7: Diğer; 8: BSC', type: 'select', options: ['1 - FUFA-XELODA', '2 - FOLFOX/XELOX', '3 - FOLFIRI/XELİRİ', '4 - CF/CX', '5 - DCF/DCX', '6 - ECF_EOF_EOX_ECX', '7 - Diğer', '8 - BSC'], category: 'Metastatik Tedavi', active: true },
  { id: 'metastatik_ilk_seri_tedavi_kur_sayisi', label: '(AX) Metastatik İlk Seri Tedavi Kür Sayısı', type: 'number', category: 'Metastatik Tedavi', active: true },
  { id: 'metastatik_ilk_seri_tedaviye_cevap', label: '(AY) Metastatik İlk Seri Tedaviye Cevap. 1: CR; 2: PR; 3: SD; 4: PD; 5: Bilinmiyor', type: 'select', options: ['1 - CR', '2 - PR', '3 - SD', '4 - PD', '5 - Bilinmiyor'], category: 'Metastatik Tedavi', active: true },
  { id: 'met_1_tedavi_sonrasi_pd', label: '(AZ) 1. Seri Tedavi Sonrası Progresyon Var Mı. 0: Progresyon Yok; 1: Progresyon Var', type: 'select', options: ['0 - Progresyon Yok', '1 - Progresyon Var'], category: 'Metastatik Tedavi', active: true },
  { id: 'met_1_tedavi_sonrasi_pd_tarihi', label: '(BA) 1. Seri Tedavi Sonrası PD Tarihi', type: 'text', category: 'Metastatik Tedavi', active: true },
  { id: 'metastatik_ilk_seri_tedavi_toksisitesi', label: '(BB) Metastatik İlk Seri Tedavi Toksisitesi', type: 'text', category: 'Metastatik Tedavi', active: true },
  { id: 'met_2_seri_tedavi_rejimi', label: '(BC) Met 2.Seri Tedavi Rejimi. 1: FUFA-XELODA; 2: FOLFOX/XELOX; 3: FOLFIRI/XELİRİ; 4: CF/CX; 5: DCF/DCX; 6: ECF/EOF/ECX/EOX; 7: Diğer; 8: BSC', type: 'select', options: ['1 - FUFA-XELODA', '2 - FOLFOX/XELOX', '3 - FOLFIRI/XELİRİ', '4 - CF/CX', '5 - DCF/DCX', '6 - ECF_EOF_ECX_EOX', '7 - Diğer', '8 - BSC'], category: 'Metastatik Tedavi', active: true },
  { id: 'met_2_seri_baslama_tarihi', label: '(BD) Met 2.Seri Başlama Tarihi', type: 'text', category: 'Metastatik Tedavi', active: true },
  { id: 'met_2_seri_kur_sayisi', label: '(BE) Met 2.Seri Kür Sayısı', type: 'number', category: 'Metastatik Tedavi', active: true },
  { id: 'met_2_seri_tedaviye_cevap', label: '(BF) Met 2.Seri Tedaviye Cevap. 1: CR; 2: PR; 3: SD; 4: PD', type: 'select', options: ['1 - CR', '2 - PR', '3 - SD', '4 - PD'], category: 'Metastatik Tedavi', active: true },
  { id: 'met_2_seri_sonrasi_pd', label: '(BG) Met 2.Seri Sonrası PD. 0: YOK; 1: VAR', type: 'select', options: ['0 - YOK', '1 - VAR'], category: 'Metastatik Tedavi', active: true },
  { id: 'met_2_seri_sonrasi_pd_tarihi', label: '(BH) Met 2.Seri Sonrası PD Tarihi', type: 'text', category: 'Metastatik Tedavi', active: true },
  { id: 'met_2_seri_tedavi_toksisitesi', label: '(BI) Met 2.Seri Tedavi Toksisitesi', type: 'text', category: 'Metastatik Tedavi', active: true },
  { id: 'met_3_seri_tedavi_rejimi', label: '(BJ) Met 3.Seri Tedavi Rejimi. 1: FUFA-XELODA; 2: FOLFOX/XELOX; 3: FOLFIRI/XELİRİ; 4: CF/CX; 5: DCF/DCX; 6: Tek Ajan Paklitaksel; 7: Diğer; 8: BSC', type: 'select', options: ['1 - FUFA-XELODA', '2 - FOLFOX/XELOX', '3 - FOLFIRI/XELİRİ', '4 - CF/CX', '5 - DCF/DCX', '6 - Tek Ajan Paklitaksel', '7 - Diğer', '8 - BSC'], category: 'Metastatik Tedavi', active: true },
  { id: 'met_3_seri_baslama_tarihi', label: '(BK) Met 3.Seri Başlama Tarihi', type: 'text', category: 'Metastatik Tedavi', active: true },
  { id: 'met_3_seri_kur_sayisi', label: '(BL) Met 3.Seri Kür Sayısı', type: 'number', category: 'Metastatik Tedavi', active: true },
  { id: 'met_3_seri_tedaviye_cevap', label: '(BM) Met 3.Seri Tedaviye Cevap. 1: CR; 2: PR; 3: SD; 4: PD', type: 'select', options: ['1 - CR', '2 - PR', '3 - SD', '4 - PD'], category: 'Metastatik Tedavi', active: true },
  { id: 'met_3_seri_sonrasi_pd', label: '(BN) Met 3.Seri Sonrası PD. 0: YOK; 1: VAR', type: 'select', options: ['0 - YOK', '1 - VAR'], category: 'Metastatik Tedavi', active: true },
  { id: 'met_3_seri_sonrasi_pd_tarihi', label: '(BO) Met 3.Seri Sonrası PD Tarihi', type: 'text', category: 'Metastatik Tedavi', active: true },
  { id: 'met_3_seri_tedavi_toksisitesi', label: '(BP) Met 3.Seri Tedavi Toksisitesi', type: 'text', category: 'Metastatik Tedavi', active: true },
  { id: 'toplam_kac_rejim_aldi', label: '(BQ) Toplam Kaç Rejim Aldı', type: 'number', category: 'Metastatik Tedavi', active: true },
  { id: 'idame_xeloda_baslama_tarihi', label: '(BR) İdame Xeloda Tedavi Başlama Tarihi', type: 'text', category: 'Metastatik Tedavi', active: true },
  { id: 'idame_xeloda_sonlandirma_tarihi', label: '(BS) İdame Xeloda Tedavi Sonlandırma Tarihi', type: 'text', category: 'Metastatik Tedavi', active: true },
  { id: 'idame_xeloda_sonrasi_progresyon_var_mi', label: '(BT) İdame Xeloda Sonrası Progresyon Var Mı. 0: YOK; 1: VAR', type: 'select', options: ['0 - YOK', '1 - VAR'], category: 'Metastatik Tedavi', active: true },
  { id: 'idame_xeloda_progresyon_tarihi', label: '(BU) İdame Xeloda Progresyon Tarihi', type: 'text', category: 'Metastatik Tedavi', active: true },
  { id: 'idame_xeloda_toksisite', label: '(BV) İdame Xeloda Toksisite', type: 'text', category: 'Metastatik Tedavi', active: true },
  { id: 'trastuzumab_kullanimi', label: '(BW) Trastuzumab Kullanımı. 0: YOK; 1: VAR', type: 'select', options: ['0 - YOK', '1 - VAR'], category: 'Klinik Sonuçlar', active: true },
  { id: 'trastuzumab_kur_sayisi', label: '(BX) Trastuzumab Kür Sayısı', type: 'number', category: 'Klinik Sonuçlar', active: true },
  { id: 'hastanin_son_durumu', label: '(BY) Hastanın Son Durumu. 0: Exitus; 1: Yaşıyor; 2: Hastalık Dışı Exitus', type: 'select', options: ['0 - Exitus', '1 - Yaşıyor', '2 - Hastalık Dışı Exitus'], category: 'Klinik Sonuçlar', active: true },
  { id: 'son_durum_tarihi', label: '(BZ) Son Durum Tarihi', type: 'text', category: 'Klinik Sonuçlar', active: true },
  { id: 'os', label: '(CA) OS (Genel Sağkalım, ay)', type: 'number', category: 'Klinik Sonuçlar', active: true },
  { id: 'dfs', label: '(CB) DFS (Hastalıksız Sağkalım, ay)', type: 'number', category: 'Klinik Sonuçlar', active: true },
  { id: 'pfs1', label: '(CC) PFS1 (1. Seri Progresyonsuz Sağkalım, ay)', type: 'number', category: 'Klinik Sonuçlar', active: true },
  { id: 'pfs2', label: '(CD) PFS2 (2. Seri Progresyonsuz Sağkalım, ay)', type: 'number', category: 'Klinik Sonuçlar', active: true },
  { id: 'pfs3', label: '(CE) PFS3 (3. Seri Progresyonsuz Sağkalım, ay)', type: 'number', category: 'Klinik Sonuçlar', active: true },
  { id: 'st1', label: '(CF) ST1', type: 'text', category: 'Klinik Sonuçlar', active: true },
  { id: 'st2', label: '(CG) ST2', type: 'text', category: 'Klinik Sonuçlar', active: true },
  { id: 'st3', label: '(CH) ST3', type: 'text', category: 'Klinik Sonuçlar', active: true },
  { id: 'ca_19_9', label: '(CI) CA 19-9', type: 'text', category: 'Klinik Sonuçlar', active: true },
  { id: 'ca_19_9_1', label: '(CJ) CA 19-9 (1. Kontrol)', type: 'text', category: 'Klinik Sonuçlar', active: true },
  { id: 'ca_19_9_2', label: '(CK) CA 19-9 (2. Kontrol)', type: 'text', category: 'Klinik Sonuçlar', active: true },
  { id: 'cea', label: '(CL) CEA', type: 'text', category: 'Klinik Sonuçlar', active: true },
  { id: 'cea_1', label: '(CM) CEA (1. Kontrol)', type: 'text', category: 'Klinik Sonuçlar', active: true },
  { id: 'cea_2', label: '(CN) CEA (2. Kontrol)', type: 'text', category: 'Klinik Sonuçlar', active: true },
  { id: 'ikinci_degerlendirme_neoadjuvan', label: '(CO) Neoadjuvan (Kontrol Değerlendirmesi)', type: 'text', category: 'İkinci Patoloji Değerlendirmesi (Kontrol)', active: true },
  { id: 'ikinci_degerlendirme_tarih', label: '(CP) Tarih (Kontrol Değerlendirmesi)', type: 'text', category: 'İkinci Patoloji Değerlendirmesi (Kontrol)', active: true },
  { id: 'ikinci_degerlendirme_operasyon', label: '(CQ) Cerrahi (Kontrol Değerlendirmesi)', type: 'text', category: 'İkinci Patoloji Değerlendirmesi (Kontrol)', active: true },
  { id: 'ikinci_degerlendirme_ekrez', label: '(CR) Ekrez', type: 'text', category: 'İkinci Patoloji Değerlendirmesi (Kontrol)', active: true },
  { id: 'ikinci_degerlendirme_ln', label: '(CS) LN (Kontrol Değerlendirmesi)', type: 'text', category: 'İkinci Patoloji Değerlendirmesi (Kontrol)', active: true },
  { id: 't_stage_2', label: '(CT) T (Kontrol Değerlendirmesi)', type: 'text', category: 'İkinci Patoloji Değerlendirmesi (Kontrol)', active: true },
  { id: 'ikinci_degerlendirme_gr', label: '(CU) GR (Kontrol Değerlendirmesi)', type: 'text', category: 'İkinci Patoloji Değerlendirmesi (Kontrol)', active: true },
  { id: 'ikinci_degerlendirme_sr_d', label: '(CV) SR/D', type: 'text', category: 'İkinci Patoloji Değerlendirmesi (Kontrol)', active: true },
  { id: 'ikinci_degerlendirme_vasc', label: '(CW) VASC (Kontrol Değerlendirmesi)', type: 'text', category: 'İkinci Patoloji Değerlendirmesi (Kontrol)', active: true },
  { id: 'ikinci_degerlendirme_lymp', label: '(CX) LYMP (Kontrol Değerlendirmesi)', type: 'text', category: 'İkinci Patoloji Değerlendirmesi (Kontrol)', active: true },
  { id: 'n_stage_2', label: '(CY) N (Kontrol Değerlendirmesi)', type: 'text', category: 'İkinci Patoloji Değerlendirmesi (Kontrol)', active: true },
  { id: 'm_stage_2', label: '(CZ) M (Kontrol Değerlendirmesi)', type: 'text', category: 'İkinci Patoloji Değerlendirmesi (Kontrol)', active: true },
  { id: 'ikinci_degerlendirme_evre', label: '(DA) Evre (Kontrol Değerlendirmesi)', type: 'text', category: 'İkinci Patoloji Değerlendirmesi (Kontrol)', active: true },
  { id: 'ikinci_degerlendirme_mln', label: '(DB) MLN (Malign Lenf Nodu)', type: 'text', category: 'İkinci Patoloji Değerlendirmesi (Kontrol)', active: true },
  { id: 'ikinci_degerlendirme_bln', label: '(DC) BLN (Benign Lenf Nodu)', type: 'text', category: 'İkinci Patoloji Değerlendirmesi (Kontrol)', active: true },
  { id: 'ikinci_degerlendirme_tln', label: '(DD) TLN (Toplam Lenf Nodu)', type: 'text', category: 'İkinci Patoloji Değerlendirmesi (Kontrol)', active: true },
  { id: 'ikinci_degerlendirme_adjuvan', label: '(DE) Adjuvan (Kontrol Değerlendirmesi)', type: 'text', category: 'İkinci Patoloji Değerlendirmesi (Kontrol)', active: true },
  { id: 'ikinci_degerlendirme_kontrol', label: '(DF) Kontrol', type: 'text', category: 'İkinci Patoloji Değerlendirmesi (Kontrol)', active: true },
  { id: 'ln_diseksiyon_sekli', label: '(DG) LN Diseksiyon Şekli', type: 'text', category: 'Ameliyat Sonrası Takip', active: true },
  { id: 'bmi', label: '(DH) BMI (Vücut Kitle İndeksi)', type: 'number', category: 'Ameliyat Sonrası Takip', active: true },
  { id: 'yatis_suresi', label: '(DI) Yatış Süresi (Gün)', type: 'text', category: 'Ameliyat Sonrası Takip', active: true },
  { id: 'dren_kalis_suresi', label: '(DJ) Dren Kalış Süresi (Gün)', type: 'text', category: 'Ameliyat Sonrası Takip', active: true },
  { id: 'gun_1_d_m', label: '(DK) 1. Gün Dren Miktarı', type: 'text', category: 'Ameliyat Sonrası Takip', active: true },
  { id: 'gun_2_d_m', label: '(DL) 2. Gün Dren Miktarı', type: 'text', category: 'Ameliyat Sonrası Takip', active: true },
  { id: 'gun_3_d_m', label: '(DM) 3. Gün Dren Miktarı', type: 'text', category: 'Ameliyat Sonrası Takip', active: true },
  { id: 'gun_4_d_m', label: '(DN) 4. Gün Dren Miktarı', type: 'text', category: 'Ameliyat Sonrası Takip', active: true },
  { id: 'gun_5_d_m', label: '(DO) 5. Gün Dren Miktarı', type: 'text', category: 'Ameliyat Sonrası Takip', active: true },
  { id: 'gun_6_d_m', label: '(DP) 6. Gün Dren Miktarı', type: 'text', category: 'Ameliyat Sonrası Takip', active: true },
  { id: 'gun_2_k_a', label: '(DQ) 2. Gün Kan Amilazı', type: 'text', category: 'Ameliyat Sonrası Takip', active: true },
  { id: 'gun_2_d_a', label: '(DR) 2. Gün Dren Amilazı', type: 'text', category: 'Ameliyat Sonrası Takip', active: true },
  { id: 'rapor', label: '(DS) Rapor', type: 'textarea', category: 'Dosya ve Rapor Bilgileri', active: true },
  { id: 'dosya_bolumu', label: '(DT) Dosya Bölümü', type: 'number', category: 'Dosya ve Rapor Bilgileri', active: true },
  { id: 'dosya_doktoru', label: '(DU) Dosya Doktoru', type: 'number', category: 'Dosya ve Rapor Bilgileri', active: true },
  { id: 'patoloji_kart_doktoru', label: '(DV) Patoloji Kart Doktoru', type: 'text', category: 'Dosya ve Rapor Bilgileri', active: true },
  { id: 'mat_kabul_tarihi', label: '(DW) Materyal Kabul Tarihi', type: 'text', category: 'Dosya ve Rapor Bilgileri', active: true },
  { id: 'rapor_cikis_tarihi', label: '(DX) Rapor Çıkış Tarihi', type: 'textarea', category: 'Dosya ve Rapor Bilgileri', active: true },
  { id: 'mat_alinma_sekli', label: '(DY) Materyal Alınma Şekli', type: 'text', category: 'Dosya ve Rapor Bilgileri', active: true },
  { id: 'mat_alindigi_organ', label: '(DZ) Materyalin Alındığı Organ', type: 'text', category: 'Dosya ve Rapor Bilgileri', active: true },
];
