
export type FieldType = 'text' | 'textarea' | 'number' | 'date' | 'select' | 'checkbox' | 'multiselect';

export interface FormField {
  id: string;
  label: string;
  type: FieldType;
  options?: string[]; // for select/multiselect
  required?: boolean;
  category: string;
  active: boolean; // Customization: active or inactive
  description?: string; // Reason for collecting this data
  dependsOn?: { fieldId: string; value: string | boolean }; // Conditional logic
}

export const defaultFormFields: FormField[] = [
  { id: 'research_id', label: '(B) DOSYA NO (Araştırma ID)', type: 'text', category: 'Genel Bilgiler', active: true },
  { id: 'ad_soyad', label: '(C) AD-SOYAD', type: 'text', category: 'Genel Bilgiler', active: true },
  { id: 't_c', label: '(D) T.C.', type: 'text', category: 'Genel Bilgiler', active: true },
  { id: 'ya', label: '(E) YAŞ', type: 'text', category: 'Demografik & Yaşam Tarzı', active: true },
  { id: 'cinsiyet', label: '(F) Cinsiyet. 1: ERKEK; 2: KADIN', type: 'select', options: ['1 - ERKEK', '2 - KADIN'], category: 'Demografik & Yaşam Tarzı', active: true },
  { id: 'per_durum', label: '(G) Per.Durum. 0: PS0; 1: PS1; 2: PS2; 3: PS3; 4: PS4; 5: BİLGİ YOK', type: 'select', options: ['0 - PS0', '1 - PS1', '2 - PS2', '3 - PS3', '4 - PS4', '5 - BİLGİ YOK'], category: 'Demografik & Yaşam Tarzı', active: true },
  { id: 'aile_oykusu', label: '(H) Aile Öyküsü. 0: YOK; 1: VAR; 2: BİLGİ YOK', type: 'select', options: ['0 - YOK', '1 - VAR', '2 - BİLGİ YOK'], category: 'Demografik & Yaşam Tarzı', active: true },
  { id: 'kilo_kaybi', label: '(I) Kilo Kaybı. 1: YOK; 2: VAR; 3: BİLGİ YOK', type: 'select', options: ['1 - YOK', '2 - VAR', '3 - BİLGİ YOK'], category: 'Demografik & Yaşam Tarzı', active: true },
  { id: 'sigara', label: '(J) Sigara. 1: YOK; 2: VAR; 3: BİLGİ YOK', type: 'select', options: ['1 - YOK', '2 - VAR', '3 - BİLGİ YOK'], category: 'Demografik & Yaşam Tarzı', active: true },
  { id: 'lokaliza', label: '(K) Lokaliza. 1: DİSTAL; 2: PROKSİMAL', type: 'select', options: ['1 - DİSTAL', '2 - PROKSİMAL'], category: 'Tümör Patolojisi & Evreleme', active: true },
  { id: 'kanser_tipi', label: '(L) Kanser Tipi. 1: Adenokarsinom; 2: Skuamöz Hücreli Ca; 3: Nöroendokrin Karsinom; 4: Lenfoma; 5: GİST', type: 'select', options: ['1 - Adenokarsinom', '2 - Skuamöz Hücreli Ca', '3 - Nöroendokrin Karsinom', '4 - Lenfoma', '5 - GİST'], category: 'Tümör Patolojisi & Evreleme', active: true },
  { id: 'histoloji_bormann', label: '(M) Histoloji Bormann. 1: Polipoid; 2: Fungal; 3: Ülseröz; 4: Diffüz İnfiltran; 5: Vegetan; 6: Ülsero Vegetan', type: 'select', options: ['1 - Polipoid', '2 - Fungal', '3 - Ülseröz', '4 - Diffüz İnfiltran', '5 - Vegetan', '6 - Ülsero Vegetan'], category: 'Tümör Patolojisi & Evreleme', active: true },
  { id: 'histoloji_who', label: '(N) Histoloji WHO. 1: Papiller; 2: Tubuler; 3: Müsinöz; 4: Taşlı Yüzük; 6: Kribriform; 7: Miks Histoloji; 8: Solid Patern', type: 'select', options: ['1 - Papiller', '2 - Tubuler', '3 - Müsinöz', '4 - Taşlı Yüzük', '6 - Kribriform', '7 - Miks Histoloji', '8 - Solid Patern'], category: 'Tümör Patolojisi & Evreleme', active: true },
  { id: 'histoloji_ming', label: '(O) Histoloji Ming. 1: İnfiltratif; 2: Ekspansif; 3: Expansif İnfitratif', type: 'select', options: ['1 - İnfiltratif', '2 - Ekspansif', '3 - Expansif İnfitratif'], category: 'Tümör Patolojisi & Evreleme', active: true },
  { id: 'lauren', label: '(P) Lauren Sınıflaması. 1: Diffüz; 2: İntestinal', type: 'select', options: ['1 - Diffüz', '2 - İntestinal'], category: 'Tümör Patolojisi & Evreleme', active: true },
  { id: 'tm_api_cm', label: '(Q) TM ÇAPI (CM)', type: 'text', category: 'Tümör Patolojisi & Evreleme', active: true },
  { id: 't', label: '(R) T. 1: T1a; 2: T1b; 3: T2; 4: T3; 5: T4a; 6: T4b', type: 'select', options: ['1 - T1a', '2 - T1b', '3 - T2', '4 - T3', '5 - T4a', '6 - T4b'], category: 'Tümör Patolojisi & Evreleme', active: true },
  { id: 'n', label: '(S) N. 0: N0; 1: N1; 2: N2; 3: N3a; 4: N3b', type: 'select', options: ['0 - N0', '1 - N1', '2 - N2', '3 - N3a', '4 - N3b'], category: 'Tümör Patolojisi & Evreleme', active: true },
  { id: 'm', label: '(T) M. 0: M0; 1: M1', type: 'select', options: ['0 - M0', '1 - M1'], category: 'Tümör Patolojisi & Evreleme', active: true },
  { id: 'tnm_evre', label: '(U) TNM EVRE', type: 'text', category: 'Tümör Patolojisi & Evreleme', active: true },
  { id: 'toplam_ln_sayisi', label: '(V) TOPLAM LN SAYISI', type: 'number', category: 'Tümör Patolojisi & Evreleme', active: true },
  { id: 'mal_gn_ln_sayisi', label: '(W) MALİGN LN SAYISI', type: 'number', category: 'Tümör Patolojisi & Evreleme', active: true },
  { id: 'lenf_invazyon', label: '(X) Lenf İnvazyon. 0: YOK; 1: VAR; 2: BİLGİ YOK', type: 'select', options: ['0 - YOK', '1 - VAR', '2 - BİLGİ YOK'], category: 'Tümör Patolojisi & Evreleme', active: true },
  { id: 'vask_infazyon', label: '(Y) Vask İnvazyon. 0: YOK; 1: VAR', type: 'select', options: ['0 - YOK', '1 - VAR'], category: 'Tümör Patolojisi & Evreleme', active: true },
  { id: 'perino_invazyon', label: '(Z) Perinö İnvazyon. 0: YOK; 1: VAR; 2: BİLGİ YOK', type: 'select', options: ['0 - YOK', '1 - VAR', '2 - BİLGİ YOK'], category: 'Tümör Patolojisi & Evreleme', active: true },
  { id: 'grade', label: '(AA) Grade. 1: Grade 1; 2: Grade 2; 3: Grade 3', type: 'select', options: ['1 - Grade 1', '2 - Grade 2', '3 - Grade 3'], category: 'Tümör Patolojisi & Evreleme', active: true },
  { id: 'ta_li_y_z_k', label: '(AB) Taşlı Yüzük. 0: YOK; 1: VAR', type: 'select', options: ['0 - YOK', '1 - VAR'], category: 'Tümör Patolojisi & Evreleme', active: true },
  { id: 'her2', label: '(AC) HER2. 0: Negatif; 1: 1+; 2: 2+; 3: 3+', type: 'select', options: ['0 - Negatif', '1 - 1+', '2 - 2+', '3 - 3+'], category: 'Tümör Patolojisi & Evreleme', active: true },
  { id: 'her2f_sh', label: '(AD) HER2FİSH. 0: Negatif; 1: Pozitif; 2: Bilgi Yok', type: 'select', options: ['0 - Negatif', '1 - Pozitif', '2 - Bilgi Yok'], category: 'Tümör Patolojisi & Evreleme', active: true },
  { id: 'mus_n', label: '(AE) Musin. 0: YOK; 1: VAR', type: 'select', options: ['0 - YOK', '1 - VAR'], category: 'Tümör Patolojisi & Evreleme', active: true },
  { id: 'cer_t_r', label: '(AF) Cer. Türü. 1: Total Gastrektomi; 2: Subtotal Gastrektomi; 3: Palyatif Rezeksiyon', type: 'select', options: ['1 - Total Gastrektomi', '2 - Subtotal Gastrektomi', '3 - Palyatif Rezeksiyon'], category: 'Cerrahi & Tedavi', active: true },
  { id: 'total_subtotal', label: '(AG) TOTAL/SUBTOTAL', type: 'text', category: 'Cerrahi & Tedavi', active: true },
  { id: 'rezeks_yon_t_p', label: '(AH) Rezeksiyon Tipi. 0: R0; 1: R1; 2: R2', type: 'select', options: ['0 - R0', '1 - R1', '2 - R2'], category: 'Cerrahi & Tedavi', active: true },
  { id: 'relaps', label: '(AI) Relaps. 0: YOK; 1: VAR; 2: BİLGİ YOK', type: 'select', options: ['0 - YOK', '1 - VAR', '2 - BİLGİ YOK'], category: 'Cerrahi & Tedavi', active: true },
  { id: 'lokal_n_ks', label: '(AJ) Lokal Nüks. 0: YOK; 1: VAR; 2: BİLGİ YOK', type: 'select', options: ['0 - YOK', '1 - VAR', '2 - BİLGİ YOK'], category: 'Cerrahi & Tedavi', active: true },
  { id: 'lokal_n_ks_tar_h', label: '(AK) LOKAL NÜKS TARİHİ', type: 'text', category: 'Cerrahi & Tedavi', active: true },
  { id: 'metastaz_var_mi', label: '(AL) Metastaz Var Mı. 0: YOK; 1: VAR', type: 'select', options: ['0 - YOK', '1 - VAR'], category: 'Cerrahi & Tedavi', active: true },
  { id: 'metastaz_yer', label: '(AM) METASTAZ YERİ', type: 'text', category: 'Cerrahi & Tedavi', active: true },
  { id: 'metastaz_tar_h', label: '(AN) METASTAZ TARİHİ', type: 'text', category: 'Cerrahi & Tedavi', active: true },
  { id: 'neoadjuvan_tedav', label: '(AO) Neoadjuvan Tedavi. 0: YOK; 1: VAR; 2: BİLGİ YOK', type: 'select', options: ['0 - YOK', '1 - VAR', '2 - BİLGİ YOK'], category: 'Cerrahi & Tedavi', active: true },
  { id: 'adjuvan_tedav', label: '(AP) Adjuvan Tedavi. 0: YOK; 1: VAR; 2: BİLGİ YOK', type: 'select', options: ['0 - YOK', '1 - VAR', '2 - BİLGİ YOK'], category: 'Cerrahi & Tedavi', active: true },
  { id: 'adjuvan_tedav_t_r', label: '(AQ) Adjuvan Tedavi Türü. 1: KTRT; 2: Sadece KT', type: 'select', options: ['1 - KTRT', '2 - Sadece KT'], category: 'Cerrahi & Tedavi', active: true },
  { id: 'adjuvan_kt', label: '(AR) Adjuvan KT. 1: FUFA-RT; 2: FOLFOX RT; 3: XELOX RT; 4: Sadece KT; 5: Bilgi Yok', type: 'select', options: ['1 - FUFA-RT', '2 - FOLFOX RT', '3 - XELOX RT', '4 - Sadece KT', '5 - Bilgi Yok'], category: 'Cerrahi & Tedavi', active: true },
  { id: 'adjuvan_tedav_k_r_sayisi', label: '(AS) ADJUVAN TEDAVİ KÜR SAYISI', type: 'number', category: 'Cerrahi & Tedavi', active: true },
  { id: 'adjuvan_tedav_tar_h', label: '(AT) ADJUVAN TEDAVİ TARİHİ', type: 'text', category: 'Cerrahi & Tedavi', active: true },
  { id: 'metastat_k_durum', label: '(AU) Metastatik Durum. 0: Progresyon Sonrası; 1: Başlangıçta Metastatik', type: 'select', options: ['0 - Progresyon Sonrası', '1 - Başlangıçta Metastatik'], category: 'Metastatik Tedavi', active: true },
  { id: 'metastaz_tar_h', label: '(AV) METASTAZ TARİHİ', type: 'text', category: 'Metastatik Tedavi', active: true },
  { id: 'metastaz_b_rser_kt', label: '(AW) Metastaz Bir. Seri KT. 1: FUFA-XELODA; 2: FOLFOX/XELOX; 3: FOLFIRI/XELİRİ; 4: CF/CX; 5: DCF/DCX; 6: ECF_EOF_EOX_ECX; 7: Diğer; 8: BSC', type: 'select', options: ['1 - FUFA-XELODA', '2 - FOLFOX/XELOX', '3 - FOLFIRI/XELİRİ', '4 - CF/CX', '5 - DCF/DCX', '6 - ECF_EOF_EOX_ECX', '7 - Diğer', '8 - BSC'], category: 'Metastatik Tedavi', active: true },
  { id: 'metastat_k_lk_ser_tedav_k_r_sayisi', label: '(AX) METASTATİK İLK SERİ TEDAVİ KÜR SAYISI', type: 'number', category: 'Metastatik Tedavi', active: true },
  { id: 'metastat_k_lk_ser_tedav_ye_cevap', label: '(AY) Metastatik İlk Seri Tedaviye Cevap. 1: CR; 2: PR; 3: SD; 4: PD; 5: Bilinmiyor', type: 'select', options: ['1 - CR', '2 - PR', '3 - SD', '4 - PD', '5 - Bilinmiyor'], category: 'Metastatik Tedavi', active: true },
  { id: 'met_1_tedav_sonrasi_pd', label: '(AZ) 1. Seri Tedavi Sonrası Progresyon Var Mı. 0: Progresyon Yok; 1: Progresyon Var', type: 'select', options: ['0 - Progresyon Yok', '1 - Progresyon Var'], category: 'Metastatik Tedavi', active: true },
  { id: 'met_1_tedav_sonrasi_pd_tar_h', label: '(BA) MET 1 TEDAVİ SONRASI PD TARİHİ', type: 'text', category: 'Metastatik Tedavi', active: true },
  { id: 'metastat_k_lk_ser_tedav_toks_s_tes', label: '(BB) METASTATİK İLK SERİ TEDAVİ TOKSİSİTESİ', type: 'text', category: 'Metastatik Tedavi', active: true },
  { id: 'met_2_ser_tedav_rej_m', label: '(BC) Met 2.Seri Tedavi Rejimi. 1: FUFA-XELODA; 2: FOLFOX/XELOX; 3: FOLFIRI/XELİRİ; 4: CF/CX; 5: DCF/DCX; 6: ECF_EOF_ECX_EOX; 7: Diğer; 8: BSC', type: 'select', options: ['1 - FUFA-XELODA', '2 - FOLFOX/XELOX', '3 - FOLFIRI/XELİRİ', '4 - CF/CX', '5 - DCF/DCX', '6 - ECF_EOF_ECX_EOX', '7 - Diğer', '8 - BSC'], category: 'Metastatik Tedavi', active: true },
  { id: 'met_2_ser_ba_lama_tar_h', label: '(BD) MET 2.SERİ BAŞLAMA TARİHİ', type: 'text', category: 'Metastatik Tedavi', active: true },
  { id: 'met_2_ser_k_r_sayisi', label: '(BE) MET 2.SERİ KÜR SAYISI', type: 'number', category: 'Metastatik Tedavi', active: true },
  { id: 'met_2_ser_tedav_ye_cevap', label: '(BF) Met 2.Seri Tedaviye Cevap. 1: CR; 2: PR; 3: SD; 4: PD', type: 'select', options: ['1 - CR', '2 - PR', '3 - SD', '4 - PD'], category: 'Metastatik Tedavi', active: true },
  { id: 'met_2_ser_sonrasi_pd', label: '(BG) Met 2.Seri Sonrası PD. 0: YOK; 1: VAR', type: 'select', options: ['0 - YOK', '1 - VAR'], category: 'Metastatik Tedavi', active: true },
  { id: 'met_2_ser_sonrasi_pd_tar_h', label: '(BH) MET 2.SERİ SONRASI PD. TARİHİ', type: 'text', category: 'Metastatik Tedavi', active: true },
  { id: 'met_2_ser_tedav', label: '(BI) MET 2.SERİ  TEDAVİ TOKSİSİTESİ', type: 'text', category: 'Metastatik Tedavi', active: true },
  { id: 'met_3_ser_tedav_rej_m', label: '(BJ) Met 3.Seri Tedavi Rejimi. 1: FUFA-XELODA; 2: FOLFOX/XELOX; 3: FOLFIRI/XELİRİ; 4: CF/CX; 5: DCF/DCX; 6: Tek Ajan Paklitaksel; 7: Diğer; 8: BSC', type: 'select', options: ['1 - FUFA-XELODA', '2 - FOLFOX/XELOX', '3 - FOLFIRI/XELİRİ', '4 - CF/CX', '5 - DCF/DCX', '6 - Tek Ajan Paklitaksel', '7 - Diğer', '8 - BSC'], category: 'Metastatik Tedavi', active: true },
  { id: 'met_3_ser_ba_lama_tar_h', label: '(BK) MET 3.SERİ BAŞLAMA TARİHİ', type: 'text', category: 'Metastatik Tedavi', active: true },
  { id: 'met_3_ser_k_r_sayisi', label: '(BL) MET 3.SERİ KÜR SAYISI', type: 'number', category: 'Metastatik Tedavi', active: true },
  { id: 'met_3_ser_tedav_ye_cevap', label: '(BM) Met 3.Seri Tedaviye Cevap. 1: CR; 2: PR; 3: SD; 4: PD', type: 'select', options: ['1 - CR', '2 - PR', '3 - SD', '4 - PD'], category: 'Metastatik Tedavi', active: true },
  { id: 'met_3_ser_sonrasi_pd', label: '(BN) Met 3.Seri Sonrası PD. 0: YOK; 1: VAR', type: 'select', options: ['0 - YOK', '1 - VAR'], category: 'Metastatik Tedavi', active: true },
  { id: 'met_3_ser_sonrasi_pd_tar_h', label: '(BO) MET 3.SERİ SONRASI PD. TARİHİ', type: 'text', category: 'Metastatik Tedavi', active: true },
  { id: 'met_3_ser_tedav_toks_s_tes', label: '(BP) MET 3.SERİ TEDAVİ TOKSİSİTESİ', type: 'text', category: 'Metastatik Tedavi', active: true },
  { id: 'toplam_ka_rej_m_aldi', label: '(BQ) TOPLAM KAÇ REJİM ALDI', type: 'text', category: 'Metastatik Tedavi', active: true },
  { id: 'dame_xeloda_tedav_ba_lama_tar_h', label: '(BR) İDAME XELODA TEDAVİ BAŞLAMA TARİHİ', type: 'text', category: 'Metastatik Tedavi', active: true },
  { id: 'dame_xeloda_tedav_sonlandirma_tar_h', label: '(BS) İDAME XELODA TEDAVİ SONLANDIRMA TARİHİ', type: 'text', category: 'Metastatik Tedavi', active: true },
  { id: 'dame_xeloda_sonrasi_progresyon_var_mi', label: '(BT) İdame Xeloda Sonrası Progresyon Var Mı. 0: YOK; 1: VAR', type: 'select', options: ['0 - YOK', '1 - VAR'], category: 'Metastatik Tedavi', active: true },
  { id: 'dame_xeloda_progresyon_tar_h', label: '(BU) İDAME XELODA PROGRESYON TARİHİ', type: 'text', category: 'Metastatik Tedavi', active: true },
  { id: 'dame_xeloda_toks_s_te', label: '(BV) İDAME XELODA TOKSİSİTE', type: 'text', category: 'Metastatik Tedavi', active: true },
  { id: 'trastuzumab_kullanimi', label: '(BW) Trastuzumab Kullanımı. 0: YOK; 1: VAR', type: 'select', options: ['0 - YOK', '1 - VAR'], category: 'Metastatik Tedavi', active: true },
  { id: 'trastuzumab_k_r_sayisi', label: '(BX) TRASTUZUMAB KÜR SAYISI', type: 'number', category: 'Metastatik Tedavi', active: true },
  { id: 'hastanin_son_durumu', label: '(BY) Hastanın Son Durumu. 0: Exitus; 1: Yaşıyor; 2: Hastalık Dışı Exitus', type: 'select', options: ['0 - Exitus', '1 - Yaşıyor', '2 - Hastalık Dışı Exitus'], category: 'Klinik Sonuçlar', active: true },
  { id: 'son_durum_tar_h', label: '(BZ) SON DURUM TARİHİ', type: 'text', category: 'Klinik Sonuçlar', active: true },
  { id: 'os', label: '(CA) OS', type: 'number', category: 'Klinik Sonuçlar', active: true },
  { id: 'dfs', label: '(CB) DFS', type: 'number', category: 'Klinik Sonuçlar', active: true },
  { id: 'pfs1', label: '(CC) PFS1', type: 'number', category: 'Klinik Sonuçlar', active: true },
  { id: 'pfs2', label: '(CD) PFS2', type: 'number', category: 'Klinik Sonuçlar', active: true },
  { id: 'pfs3', label: '(CE) PFS3', type: 'number', category: 'Klinik Sonuçlar', active: true },
  { id: 'st1', label: '(CF) ST1', type: 'text', category: 'Klinik Sonuçlar', active: true },
  { id: 'st2', label: '(CG) ST2', type: 'text', category: 'Klinik Sonuçlar', active: true },
  { id: 'st3', label: '(CH) ST3', type: 'text', category: 'Klinik Sonuçlar', active: true },
  { id: 'ca_19_9', label: '(CI) CA 19-9', type: 'text', category: 'Klinik Sonuçlar', active: true },
  { id: 'ca_19_9_1', label: '(CJ) CA 19-9/1', type: 'text', category: 'Klinik Sonuçlar', active: true },
  { id: 'ca_19_9_2', label: '(CK) CA 19-9/2', type: 'text', category: 'Klinik Sonuçlar', active: true },
  { id: 'cea', label: '(CL) CEA', type: 'text', category: 'Klinik Sonuçlar', active: true },
  { id: 'cea_1', label: '(CM) CEA/1', type: 'text', category: 'Klinik Sonuçlar', active: true },
  { id: 'cea_2', label: '(CN) CEA/2', type: 'text', category: 'Klinik Sonuçlar', active: true },
  { id: 'neoadjuvan', label: '(CO) NEOADJUVAN', type: 'text', category: 'Klinik Sonuçlar', active: true },
  { id: 'tar_h', label: '(CP) TARİH', type: 'text', category: 'Klinik Sonuçlar', active: true },
  { id: 'cerrah', label: '(CQ) CERRAHİ', type: 'text', category: 'Klinik Sonuçlar', active: true },
  { id: 'ekrez', label: '(CR) EKREZ', type: 'text', category: 'Klinik Sonuçlar', active: true },
  { id: 'ln', label: '(CS) LN', type: 'text', category: 'Klinik Sonuçlar', active: true },
  { id: 't', label: '(CT) T', type: 'text', category: 'Klinik Sonuçlar', active: true },
  { id: 'gr', label: '(CU) GR', type: 'text', category: 'Klinik Sonuçlar', active: true },
  { id: 'sr_d', label: '(CV) SR/D', type: 'text', category: 'Klinik Sonuçlar', active: true },
  { id: 'vasc', label: '(CW) VASC', type: 'text', category: 'Klinik Sonuçlar', active: true },
  { id: 'lymp', label: '(CX) LYMP', type: 'text', category: 'Klinik Sonuçlar', active: true },
  { id: 'n', label: '(CY) N', type: 'text', category: 'Klinik Sonuçlar', active: true },
  { id: 'm', label: '(CZ) M', type: 'text', category: 'Klinik Sonuçlar', active: true },
  { id: 'evre', label: '(DA) EVRE', type: 'text', category: 'Klinik Sonuçlar', active: true },
  { id: 'mln', label: '(DB) MLN', type: 'text', category: 'Klinik Sonuçlar', active: true },
  { id: 'bln', label: '(DC) BLN', type: 'text', category: 'Klinik Sonuçlar', active: true },
  { id: 'tln', label: '(DD) TLN', type: 'text', category: 'Klinik Sonuçlar', active: true },
  { id: 'adjuvan', label: '(DE) ADJUVAN', type: 'text', category: 'Klinik Sonuçlar', active: true },
  { id: 'kontrol', label: '(DF) KONTROL', type: 'text', category: 'Klinik Sonuçlar', active: true },
  { id: 'ln_d_seks_yon_ekl', label: '(DG) LN DİSEKSİYON ŞEKLİ', type: 'text', category: 'Klinik Sonuçlar', active: true },
  { id: 'bmi', label: '(DH) BMI', type: 'number', category: 'Klinik Sonuçlar', active: true },
  { id: 'yati_s_res', label: '(DI) YATIŞ SÜRESİ', type: 'text', category: 'Klinik Sonuçlar', active: true },
  { id: 'dren_kali_s_res', label: '(DJ) DREN KALIŞ SÜRESİ', type: 'text', category: 'Klinik Sonuçlar', active: true },
  { id: '1_g_n_d_m', label: '(DK) 1.GÜN D M', type: 'text', category: 'Klinik Sonuçlar', active: true },
  { id: '2_g_n_d_m', label: '(DL) 2. GÜN D M', type: 'text', category: 'Klinik Sonuçlar', active: true },
  { id: '3_g_n_d_m', label: '(DM) 3.GÜN D M', type: 'text', category: 'Klinik Sonuçlar', active: true },
  { id: '4_g_n_d_m', label: '(DN) 4. GÜN D M', type: 'text', category: 'Klinik Sonuçlar', active: true },
  { id: '5_g_n_d_m', label: '(DO) 5. GÜN D M', type: 'text', category: 'Klinik Sonuçlar', active: true },
  { id: '6_g_n_d_m', label: '(DP) 6. GÜN D M', type: 'text', category: 'Klinik Sonuçlar', active: true },
  { id: '2_g_n_k_a', label: '(DQ) 2. GÜN K A', type: 'text', category: 'Klinik Sonuçlar', active: true },
  { id: '2_g_n_d_a', label: '(DR) 2. GÜN D A', type: 'text', category: 'Klinik Sonuçlar', active: true },
  { id: 'rapor', label: '(DS) RAPOR', type: 'textarea', category: 'Klinik Sonuçlar', active: true },
  { id: 'dosya_b_l_m', label: '(DT) DOSYA BÖLÜMÜ', type: 'number', category: 'Klinik Sonuçlar', active: true },
  { id: 'dosya_doktoru', label: '(DU) DOSYA DOKTORU', type: 'number', category: 'Klinik Sonuçlar', active: true },
  { id: 'patoloj_kart_doktoru', label: '(DV) PATOLOJİ KART DOKTORU', type: 'text', category: 'Klinik Sonuçlar', active: true },
  { id: 'mat_kabul_tar_h', label: '(DW) MAT.KABUL TARİHİ', type: 'text', category: 'Klinik Sonuçlar', active: true },
  { id: 'rapor_iki_tar_h', label: '(DX) RAPOR ÇIKIŞ TARİHİ', type: 'textarea', category: 'Klinik Sonuçlar', active: true },
  { id: 'mat_alinma_ekl', label: '(DY) MAT.ALINMA ŞEKLİ', type: 'text', category: 'Klinik Sonuçlar', active: true },
  { id: 'mat_alindi_i_organ', label: '(DZ) MAT.ALINDIĞI ORGAN', type: 'text', category: 'Klinik Sonuçlar', active: true }
];
