const fs = require('fs');
let schema = fs.readFileSync('src/lib/schema.ts', 'utf8');

schema = schema.replace(
  /export const defaultFormFields: FormField\[\] = \[[\s\S]*?\];/,
  `export const defaultFormFields: FormField[] = [
  // Demografik & Yaşam Tarzı
  { id: 'cinsiyet', label: 'Cinsiyet', type: 'select', options: ['1 - Erkek', '2 - Kadın'], category: 'Demografik & Yaşam Tarzı', active: true, description: 'Kodlama Açıklaması: 1: Erkek, 2: Kadın.' },
  { id: 'yas', label: 'Yaş', type: 'number', category: 'Demografik & Yaşam Tarzı', active: true, description: 'Hastanın yaşı' },
  { id: 'ethnicity', label: 'Etnik Köken / Irk', type: 'text', category: 'Demografik & Yaşam Tarzı', active: true, description: 'Doğu Asya ve Doğu Avrupa populasyonlarında insidans yüksektir.' },
  { id: 'bmi', label: 'Vücut Kitle İndeksi (BMI)', type: 'number', category: 'Demografik & Yaşam Tarzı', active: true, description: 'Yüksek Vücut Kitle İndeksi (obezite), özellikle gastroözofageal bileşke (GEJ) ve kardiya yerleşimli adenocarcinoma için bağımsız risk faktörüdür.' },
  { id: 'sigara', label: 'Sigara Kullanımı', type: 'select', options: ['1 - Yok', '2 - Var', '3 - Bilgi Yok'], category: 'Demografik & Yaşam Tarzı', active: true, description: 'Kodlama Açıklaması: Tütün kullanımı risk oranını 1.5-2 kat artırır.' },
  { id: 'alcohol', label: 'Alkol Kullanımı', type: 'select', options: ['Kullanmıyor', 'Bırakmış', 'Aktif Kullanıcı'], category: 'Demografik & Yaşam Tarzı', active: true, description: 'Kronik alkol kullanımı, gastrik mukoza bariyerinde hasar ve asetaldehit birikimi oluşturarak malign transformasyonu tetikler.' },
  { id: 'diet', label: 'Beslenme Alışkanlıkları', type: 'multiselect', options: ['Yüksek Tuz Tüketimi', 'Tütsülenmiş/İşlenmiş Et', 'Düşük Meyve/Sebze'], category: 'Demografik & Yaşam Tarzı', active: true, description: 'Tuzlanmış/tütsülenmiş gıdalar (nitrosaminler) endojen karsinojenik etki yapar.' },
  { id: 'blood_type', label: 'Kan Grubu', type: 'select', options: ['A', 'B', 'AB', '0', 'Bilinmiyor'], category: 'Demografik & Yaşam Tarzı', active: true, description: 'A kan grubu taşıyıcılarında gastrik kanser insidansı %20 daha yüksektir.' },
  { id: 'aile_oykusu', label: 'Aile Öyküsü', type: 'select', options: ['0 - Yok', '1 - Var', '2 - Bilgi Yok'], category: 'Demografik & Yaşam Tarzı', active: true, description: 'Kodlama Açıklaması: Ailede kanser öyküsü.' },

  // Klinik & Laboratuvar
  { id: 'per_durum', label: 'Performans Durumu', type: 'select', options: ['0 - PS0', '1 - PS1', '2 - PS2', '3 - PS3', '4 - PS4', '5 - Bilgi Yok'], category: 'Klinik & Laboratuvar', active: true, description: 'Kodlama Açıklaması: Hastanın genel performans durumu.' },
  { id: 'kilo_kaybi', label: 'Kilo Kaybı (Son 6 Ay)', type: 'select', options: ['1 - Yok', '2 - Var', '3 - Bilgi Yok'], category: 'Klinik & Laboratuvar', active: true, description: 'Kodlama Açıklaması: Son 6 ayda kilo kaybı öyküsü.' },
  { id: 'clinical_notes', label: 'Klinik Notlar / Ekstre Metin', type: 'textarea', category: 'Klinik & Laboratuvar', active: true, description: 'OCR ile aktarılan patoloji raporları, epikrizler, endoskopi özetleri ve klinik değerlendirmelerin tutulduğu esnek ham metin alanı.' },
  { id: 'h_pylori', label: 'H. Pylori Enfeksiyonu', type: 'select', options: ['Pozitif', 'Eradike Edilmiş', 'Negatif', 'Bilinmiyor'], category: 'Klinik & Laboratuvar', active: true, description: 'Helicobacter pylori, WHO Sınıf 1 karsinojendir.' },
  { id: 'ebv_serology', label: 'EBV Serolojisi', type: 'select', options: ['Pozitif', 'Negatif', 'Bilinmiyor'], category: 'Klinik & Laboratuvar', active: true, description: 'EBV serolojisi.' },
  
  // Somatik Genetik & İmmünoloji (Tümör)
  { id: 'somatic_testing_done', label: 'Somatik / Moleküler Test (Tümörden) Yapıldı mı?', type: 'checkbox', category: 'Somatik Genetik & İmmünoloji (Tümör)', active: true, description: 'Tümör dokusundan moleküler profilleme (IHC, FISH, Somatik NGS) yapılıp yapılmadığını gösterir.' },
  { id: 'her2', label: 'HER2 Ekspresyonu', type: 'select', options: ['0 - Negatif', '1 - 1+', '2 - 2+', '3 - 3+'], category: 'Somatik Genetik & İmmünoloji (Tümör)', active: true, dependsOn: { fieldId: 'somatic_testing_done', value: true }, description: 'Kodlama Açıklaması: HER2 (ERBB2) aşırı ekspresyonu.' },
  { id: 'her2fish', label: 'HER2 FISH', type: 'select', options: ['0 - Negatif', '1 - Pozitif', '2 - Bilgi Yok'], category: 'Somatik Genetik & İmmünoloji (Tümör)', active: true, dependsOn: { fieldId: 'somatic_testing_done', value: true }, description: 'Kodlama Açıklaması: HER2 FISH sonucu.' },
  { id: 'msi_status', label: 'MSI (Mikrosatellit İnstabilitesi)', type: 'select', options: ['MSI-H (dMMR)', 'MSS (pMMR)', 'Bakılmadı'], category: 'Somatik Genetik & İmmünoloji (Tümör)', active: true, dependsOn: { fieldId: 'somatic_testing_done', value: true }, description: 'MSI-H (dMMR) tümörler yüksek neoantijen yüküne sahiptir.' },
  { id: 'pdl1_cps', label: 'PD-L1 CPS Skoru', type: 'select', options: ['CPS < 1', 'CPS 1-4', 'CPS ≥ 5', 'CPS ≥ 10', 'Bakılmadı'], category: 'Somatik Genetik & İmmünoloji (Tümör)', active: true, dependsOn: { fieldId: 'somatic_testing_done', value: true }, description: 'Combined Positive Score (CPS) ≥5 veya ≥10 olması, metastatik adenokarsinomda kemoterapiye Nivolumab veya Pembrolizumab eklenmesi için sağkalım biyobelirteçtir.' },
  { id: 'ebv_ish', label: 'EBV (EBER-ISH)', type: 'select', options: ['Pozitif', 'Negatif', 'Bakılmadı'], category: 'Somatik Genetik & İmmünoloji (Tümör)', active: true, dependsOn: { fieldId: 'somatic_testing_done', value: true }, description: 'Tümör dokusunda EBER-ISH pozitifliği.' },
  { id: 'somatic_ngs', label: 'Diğer Tümör Mutasyonları (NGS)', type: 'multiselect', options: ['PIK3CA', 'ARID1A', 'KRAS', 'CTNNB1', 'Yok'], category: 'Somatik Genetik & İmmünoloji (Tümör)', active: true, dependsOn: { fieldId: 'somatic_testing_done', value: true }, description: 'Diğer somatik mutasyonlar.' },

  // Tümör Patolojisi & Evreleme
  { id: 'kanser_tipi', label: 'Kanser Tipi', type: 'select', options: ['1 - Adenokarsinom', '2 - Skuamöz Hücreli Ca', '3 - Nöroendokrin Karsinom', '4 - Lenfoma', '5 - GİST'], category: 'Tümör Patolojisi & Evreleme', active: true, description: 'Kodlama Açıklaması: Tümörün temel histolojik tipi.' },
  { id: 'lokaliza', label: 'Tümör Lokalizasyonu', type: 'select', options: ['1 - Distal', '2 - Proksimal'], category: 'Tümör Patolojisi & Evreleme', active: true, description: 'Kodlama Açıklaması: Kardiya/GEJ tümörleri obezite ve reflü ile; non-kardiya tümörler H. pylori ile ilişkilidir.' },
  { id: 'histoloji_bormann', label: 'Makroskobik Tümör Tipi (Kolon M / Bormann)', type: 'select', options: ['1 - Polipoid', '2 - Fungal', '3 - Ülseröz', '4 - Diffüz İnfiltran', '5 - Vegetan', '6 - Ülsero Vegetan'], category: 'Tümör Patolojisi & Evreleme', active: true, description: 'Kodlama Açıklaması (Excel Satır 1-2 / Kolon M): 1: Polipoid, 2: Fungal, 3: Ülseröz, 4: Diffüz İnfiltran, 5: Vegetan, 6: Ülsero Vegetan.' },
  { id: 'histoloji', label: 'Lauren Klasifikasyonu', type: 'select', options: ['1 - Diffüz', '2 - İntestinal'], category: 'Tümör Patolojisi & Evreleme', active: true, description: 'Kodlama Açıklaması: 1: Diffüz, 2: İntestinal.' },
  { id: 'histoloji_who', label: 'WHO Histolojik Tipi', type: 'select', options: ['1 - Papiller', '2 - Tubuler', '3 - Müsinöz', '4 - Taşlı Yüzük', '6 - Kribriform', '7 - Miks Histoloji', '8 - Solid Patern'], category: 'Tümör Patolojisi & Evreleme', active: true, description: 'Kodlama Açıklaması: WHO histolojik tipi.' },
  { id: 'histoloji_ming', label: 'Histoloji Ming', type: 'select', options: ['1 - İnfiltratif', '2 - Ekspansif', '3 - Expansif İnfitratif'], category: 'Tümör Patolojisi & Evreleme', active: true, description: 'Kodlama Açıklaması: Ming Histolojik sınıflaması.' },
  { id: 'grade', label: 'Histolojik Derece (Grade)', type: 'select', options: ['1', '2', '3'], category: 'Tümör Patolojisi & Evreleme', active: true, description: 'Kodlama Açıklaması: Histolojik diferansiyasyon derecesi (1-3).' },
  { id: 'tasli_yuzuk', label: 'Taşlı Yüzük', type: 'select', options: ['0 - Yok', '1 - Var'], category: 'Tümör Patolojisi & Evreleme', active: true, description: 'Kodlama Açıklaması: Taşlı yüzük hücre varlığı.' },
  { id: 'musin', label: 'Müsin', type: 'select', options: ['0 - Yok', '1 - Var'], category: 'Tümör Patolojisi & Evreleme', active: true, description: 'Kodlama Açıklaması: Müsin varlığı.' },
  { id: 'lenf_invazyon', label: 'Lenfovasküler İnvazyon (LVI)', type: 'select', options: ['0 - Yok', '1 - Var', '2 - Bilgi Yok'], category: 'Tümör Patolojisi & Evreleme', active: true, description: 'Kodlama Açıklaması: Lenfovasküler İnvazyon varlığı.' },
  { id: 'vask_infazyon', label: 'Vasküler İnvazyon', type: 'select', options: ['0 - Yok', '1 - Var'], category: 'Tümör Patolojisi & Evreleme', active: true, description: 'Kodlama Açıklaması: Vasküler İnvazyon varlığı.' },
  { id: 'perino_invazyon', label: 'Perinöral İnvazyon (PNI)', type: 'select', options: ['0 - Yok', '1 - Var', '2 - Bilgi Yok'], category: 'Tümör Patolojisi & Evreleme', active: true, description: 'Kodlama Açıklaması: Perinöral İnvazyon varlığı.' },
  { id: 't_stage', label: 'T Evresi (Tümör)', type: 'select', options: ['T1a', 'T1b', 'T2', 'T3', 'T4a', 'T4b'], category: 'Tümör Patolojisi & Evreleme', active: true, description: 'Tümörün mide duvarı katmanlarındaki derinliği.' },
  { id: 'n', label: 'N Evresi (Nod)', type: 'select', options: ['0 - N0', '1 - N1', '2 - N2', '3 - N3a', '4 - N3b'], category: 'Tümör Patolojisi & Evreleme', active: true, description: 'Kodlama Açıklaması: Metastatik lenf nodu evresi (N0-N3b).' },
  { id: 'm_stage', label: 'M Evresi (Metastaz)', type: 'select', options: ['M0 (Yok)', 'M1 (Uzak Organ/Periton)'], category: 'Tümör Patolojisi & Evreleme', active: true, description: 'M1 (uzak organ veya peritoneal metastaz).' },
  
  // Cerrahi & Tedavi
  { id: 'treatment_intent', label: 'Tedavi Amacı', type: 'select', options: ['Küratif', 'Palyatif', 'Neoadjuvan Sonrası Küratif'], category: 'Cerrahi & Tedavi', active: true, description: 'Tedavinin küratif (şifa hedefli) mi yoksa palyatif mi olacağını belirleyen multidisipliner onkoloji konseyi kararıdır.' },
  { id: 'cer_turu', label: 'Cerrahi Prosedür', type: 'select', options: ['1 - Total Gastrektomi', '2 - Subtotal Gastrektomi', '3 - Palyatif Rezeksiyon'], category: 'Cerrahi & Tedavi', active: true, description: 'Kodlama Açıklaması: Uygulanan cerrahi tip.' },
  { id: 'total_subtotal', label: 'Total/Subtotal', type: 'text', category: 'Cerrahi & Tedavi', active: true, description: 'Kodlama Açıklaması: Total veya subtotal durumu.' },
  { id: 'lymph_node_dissection', label: 'Lenf Nodu Diseksiyon Genişliği', type: 'select', options: ['D0', 'D1', 'D1+', 'D2', 'D2+'], category: 'Cerrahi & Tedavi', active: true, description: 'D2 lenfadenektomi (perigastrik + çölyak aks dalları) standart küratif cerrahi gereksinimdir.' },
  { id: 'retrieved_ln', label: 'Çıkarılan Lenf Nodu Sayısı', type: 'number', category: 'Cerrahi & Tedavi', active: true, description: 'Doğru evreleme için patolojik incelemede en az 16 (ideal olarak ≥30) lenf nodu çıkarılmış olmalıdır.' },
  { id: 'positive_ln', label: 'Metastatik Lenf Nodu Sayısı', type: 'number', category: 'Cerrahi & Tedavi', active: true, description: 'Kanser hücresi tutulumu saptanan lenf nodu sayısı.' },
  { id: 'rezeksiyon_tipi', label: 'Rezeksiyon Sınırı (R)', type: 'select', options: ['0 - R0', '1 - R1', '2 - R2'], category: 'Cerrahi & Tedavi', active: true, description: 'Kodlama Açıklaması: R0, R1 veya R2 rezeksiyon durumu.' },
  { id: 'neoadjuvan_tedavi', label: 'Neoadjuvan Tedavi', type: 'select', options: ['0 - Yok', '1 - Var', '2 - Bilgi Yok'], category: 'Cerrahi & Tedavi', active: true, description: 'Kodlama Açıklaması: Neoadjuvan tedavi durumu.' },
  { id: 'adjuvan_tedavi', label: 'Adjuvan Tedavi', type: 'select', options: ['0 - Yok', '1 - Var', '2 - Bilgi Yok'], category: 'Cerrahi & Tedavi', active: true, description: 'Kodlama Açıklaması: Adjuvan tedavi durumu.' },
  { id: 'adjuvan_tedavi_turu', label: 'Adjuvan Tedavi Türü', type: 'select', options: ['1 - KTRT', '2 - Sadece KT'], category: 'Cerrahi & Tedavi', active: true, description: 'Kodlama Açıklaması: Adjuvan tedavi türü.' },
  { id: 'adjuvan_kt', label: 'Adjuvan KT', type: 'select', options: ['1 - FUFA-RT', '2 - FOLFOX RT', '3 - XELOX RT', '4 - Sadece KT', '5 - Bilgi Yok'], category: 'Cerrahi & Tedavi', active: true, description: 'Kodlama Açıklaması: Adjuvan KT rejimleri.' },
  { id: 'relaps', label: 'Relaps', type: 'select', options: ['0 - Relaps Yok', '1 - Relaps Var', '2 - Bilgi Yok'], category: 'Cerrahi & Tedavi', active: true, description: 'Kodlama Açıklaması: Hastalık relaps durumu.' },
  { id: 'lokal_nuks', label: 'Lokal Nüks', type: 'select', options: ['0 - Yok', '1 - Var', '2 - Bilgi Yok'], category: 'Cerrahi & Tedavi', active: true, description: 'Kodlama Açıklaması: Lokal nüks durumu.' },
  { id: 'lokal_nuks_tarihi', label: 'Lokal Nüks Tarihi', type: 'date', category: 'Cerrahi & Tedavi', active: true, description: 'Kodlama Açıklaması: Lokal nüks görüldüğü tarih.' },
  { id: 'metastaz_var_mi', label: 'Metastaz Var Mı', type: 'select', options: ['0 - Yok', '1 - Var'], category: 'Cerrahi & Tedavi', active: true, description: 'Kodlama Açıklaması: Metastaz durumu.' },
  { id: 'metastaz_yeri', label: 'Metastaz Yeri', type: 'text', category: 'Cerrahi & Tedavi', active: true, description: 'Kodlama Açıklaması: Metastazın bulunduğu bölge.' },
  { id: 'metastaz_tarihi', label: 'Metastaz Tarihi', type: 'date', category: 'Cerrahi & Tedavi', active: true, description: 'Kodlama Açıklaması: Metastaz tarihi.' },
  
  // Metastatik Tedavi & Takip (Eklenen alanlar)
  { id: 'metastatik_durum', label: 'Metastatik Durum', type: 'select', options: ['0 - Progresyon Sonrası', '1 - Başlangıçta Metastatik'], category: 'Cerrahi & Tedavi', active: true, description: 'Kodlama Açıklaması: Metastatik durum.' },
  { id: 'metastaz_birserikt', label: 'Metastaz İlk Seri KT', type: 'select', options: ['1 - FUFA-XELODA', '2 - FOLFOX/XELOX', '3 - FOLFIRI/XELİRİ', '4 - CF/CX', '5 - DCF/DCX', '6 - ECF_EOF_EOX_ECX', '7 - Diğer', '8 - BSC'], category: 'Cerrahi & Tedavi', active: true, description: 'Kodlama Açıklaması: Metastatik ilk seri tedavi rejimi.' },
  { id: 'metastatik_ilk_seri_tedaviye_cevap', label: 'Metastatik İlk Seri Tedaviye Cevap', type: 'select', options: ['1 - CR', '2 - PR', '3 - SD', '4 - PD', '5 - Bilinmiyor'], category: 'Cerrahi & Tedavi', active: true, description: 'Kodlama Açıklaması: İlk seri tedaviye verilen cevap.' },
  { id: 'met_1_tedavi_sonrasi_pd', label: 'Metastatik 1. Tedavi Sonrası PD', type: 'select', options: ['0 - Progresyon Yok', '1 - Progresyon Var'], category: 'Cerrahi & Tedavi', active: true, description: 'Kodlama Açıklaması: 1. seri tedavi sonrası progresyon durumu.' },
  { id: 'met_2_seri_tedavi_rejimi', label: 'Metastaz 2. Seri Tedavi Rejimi', type: 'select', options: ['1 - FUFA-XELODA', '2 - FOLFOX/XELOX', '3 - FOLFIRI/XELİRİ', '4 - CF/CX', '5 - DCF/DCX', '6 - ECF_EOF_ECX_EOX', '7 - Diğer', '8 - BSC'], category: 'Cerrahi & Tedavi', active: true, description: 'Kodlama Açıklaması: Metastatik 2. seri tedavi rejimi.' },
  { id: 'met_2_seri_tedaviye_cevap', label: 'Metastatik 2. Seri Tedaviye Cevap', type: 'select', options: ['1 - CR', '2 - PR', '3 - SD', '4 - PD'], category: 'Cerrahi & Tedavi', active: true, description: 'Kodlama Açıklaması: 2. seri tedaviye verilen cevap.' },
  { id: 'met_2_seri_sonrasi_pd', label: 'Metastatik 2. Seri Sonrası PD', type: 'select', options: ['0 - Progresyon Yok', '1 - Progresyon Var'], category: 'Cerrahi & Tedavi', active: true, description: 'Kodlama Açıklaması: 2. seri tedavi sonrası progresyon durumu.' },
  { id: 'met_3_seri_tedavi_rejimi', label: 'Metastaz 3. Seri Tedavi Rejimi', type: 'select', options: ['1 - FUFA-XELODA', '2 - FOLFOX/XELOX', '3 - FOLFIRI/XELİRİ', '4 - CF/CX', '5 - DCF/DCX', '6 - Tek Ajan Paklitaksel', '7 - Diğer', '8 - BSC'], category: 'Cerrahi & Tedavi', active: true, description: 'Kodlama Açıklaması: Metastatik 3. seri tedavi rejimi.' },
  { id: 'met_3_seri_tedaviye_cevap', label: 'Metastatik 3. Seri Tedaviye Cevap', type: 'select', options: ['1 - CR', '2 - PR', '3 - SD', '4 - PD'], category: 'Cerrahi & Tedavi', active: true, description: 'Kodlama Açıklaması: 3. seri tedaviye verilen cevap.' },
  { id: 'met_3_seri_sonrasi_pd', label: 'Metastatik 3. Seri Sonrası PD', type: 'select', options: ['0 - Progresyon Yok', '1 - Progresyon Var'], category: 'Cerrahi & Tedavi', active: true, description: 'Kodlama Açıklaması: 3. seri tedavi sonrası progresyon durumu.' },
  { id: 'idame_xeloda_sonrasi_progresyon_var_mi', label: 'İdame Xeloda Sonrası Progresyon', type: 'select', options: ['0 - Progresyon Yok', '1 - Progresyon Var'], category: 'Cerrahi & Tedavi', active: true, description: 'Kodlama Açıklaması: İdame tedavisi sonrası progresyon.' },
  { id: 'trastuzumab_kullanimi', label: 'Trastuzumab Kullanımı', type: 'select', options: ['0 - Yok', '1 - Var'], category: 'Cerrahi & Tedavi', active: true, description: 'Kodlama Açıklaması: Trastuzumab (Herceptin) kullanımı.' },
  { id: 'hastanin_son_durumu', label: 'Hastanın Son Durumu', type: 'select', options: ['0 - Exitus', '1 - Yaşıyor', '2 - Hastalık Dışı Exitus'], category: 'Cerrahi & Tedavi', active: true, description: 'Kodlama Açıklaması: Hastanın klinik takibi.' },
  { id: 'medical_oncology', label: 'Medikal / Radyoterapi Tedavileri', type: 'multiselect', options: ['Neoadjuvan Kemoterapi (FLOT vd.)', 'Adjuvan Kemoterapi', 'Kemoradyoterapi', 'İmmünoterapi (Nivolumab vd.)', 'Hedefe Yönelik (Trastuzumab, Zolbetuximab)', 'Hiçbiri'], category: 'Cerrahi & Tedavi', active: true, description: 'Neoadjuvan/adjuvan kemoterapi (FLOT), immünoterapi ve akıllı ilaçlar (Trastuzumab, Zolbetuximab) ile hastaya özel tedavi protokolü.' }
];`
);

fs.writeFileSync('src/lib/schema.ts', schema);
console.log("Schema updated in file.");
